AccountProject/AccountProject/urls.py
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    url(r'',include('login.urls')),
    url(r'^myprofile/',include('myprofile.urls')),
    url(r'^myfile/',include('myfile.urls'))
]

AccountProject/login/urls.py
from django.urls import path
from django.conf.urls import url,include
from login import views
from django.views.generic import TemplateView
app_name="login"

urlpatterns = [
    path('', views.homePage,name='homePage'),
    path('login', views.submit_login,name='submit_login'),
    path('registration', views.submit_registration,name='submit_registration'),
    url(r'^registerpage/$', TemplateView.as_view(template_name='registerPage/register.html'), name='register'),
]

AccountProject/myfile/urls.py
from django.urls import path
from django.conf.urls import url,include
from myfile import views
from django.views.generic import TemplateView
app_name="myfile"
urlpatterns = [
    path('home', views.home,name='home'),
    path('upload', views.uploadFile,name='uploadfile'),
    path('uploaded', views.uploadedFile,name='uploadedfile'),
    path('addFileButton', views.addFileButton,name='addFileButton'),
    path('deleteDB', views.deleteDB,name='deleteDB'),
    url(r'^deleteFile/(?P<id>[0-9]+)/$', views.deleteFile,name='deleteFile'),
]

AccountProject/myprofile/urls.py
from django.urls import path
from django.conf.urls import url,include
from myprofile import views
from django.views.generic import TemplateView
app_name="myprofile"
urlpatterns = [
    path('', views.myprofile,name='myprofile'),
    path('editprofile', views.editprofile,name='editprofile'),
    path('editprofilesubmit', views.editprofilesubmit,name='editprofilesubmit')
    
]

AccountProject/login/models.py
from django.db import models

class User(models.Model):
    firstName = models.CharField(max_length = 60)
    lastName = models.CharField(max_length=60)
    userName= models.CharField(max_length = 60,primary_key=True)
    password= models.CharField(max_length = 60)
    email= models.CharField(max_length=60)
    phoneNumber= models.CharField(max_length = 60)
    def __str__(self):
        return f'User name:{self.firstName}'

# Create your models here.

AccountProject/myfile/models.py
from django.db import models


class File (models.Model):
   user = models.CharField(max_length=100)
   name = models.CharField(max_length=100)
   file = models.FileField(upload_to='media/')
   date = models.DateField(auto_now_add=True)
   

AccountProject/myprofile/models.py
from django.db import models

# Create your models here.

AccountProject/sendPdfs/models.py
from django.db import models

# Create your models here.
class mergedFile (models.Model):
   user = models.CharField(max_length=100)
   name = models.CharField(max_length=100)
   file = models.FileField(upload_to='MergedPdfs/')
   date = models.DateField(auto_now_add=True)

AccountProject/login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from login.models import User
from django.contrib import messages
import threading 
from sendPdfs.views import mergeAndSend


def homePage(request):
    return render(request,'loginPage/login.html',{}) 
    
def submit_login(request):
    # כפתור התחברות אחרי שהכנסנו נתונים
    userName=request.POST.get('username', None)
    password=request.POST.get('password', None)
    user=User.objects.filter(userName=userName).filter(password=password)
    if not user:
        return render(request,'loginPage/login.html',{})
    global now_user
    now_user=user[0]
    global t
    t = threading.Thread(target=mergeAndSend,args=(now_user,))
    t.start()
    return render(request,f'users/client.html',{'user':(user[0])}) 

def submit_registration(request):
    #כפתור הרשמה אחרי שמלאנו פרטים 
    user=User()
    user.firstName=request.POST['firstName']
    user.lastName=request.POST['lastName']
    user.userName=request.POST['userName']
    user.password=request.POST['password']
    user.email=request.POST['Email']
    user.phoneNumber = request.POST['phoneNumber']
    user.phoneNumber = '+972'+ user.phoneNumber[1:]
    print(user.phoneNumber)
    userTest=User.objects.filter(userName=user.userName)
    if userTest :
        #הודעה שהשם משתמש כבר תפוס
        messages.success(request, 'User Already In Registered')
        return render(request,'registerPage/register.html',{})
    user.save()
    return render(request,'loginPage/login.html',{}) 
def getNowUser():
    return now_user

AccountProject/myfile/views.py
from django.shortcuts import render
from myfile.models import File
from sendPdfs.models import mergedFile
from login.views import getNowUser
from django.contrib import messages
import os
import datetime
from threading import Timer


def home(request):
    user=(getNowUser())
    return render(request,'users/client.html',{'user':user})

def addFileButton(request):
    user=(getNowUser())
    fileInput = request.FILES.getlist('fileInput')
    for textFile in fileInput:
        fullName=textFile._name
        txt_name=fullName.split(".")[0]
        file=File(name=txt_name,file=textFile,user=(user.userName))
        file.save()
    messages.success(request, 'Uploaded successfully, Click to upload more')
    return render(request, 'users/client.html',{'user':user})

def deleteFile(request,id):
    deleteFile = File.objects.get(id=id)
    deleteFile.delete()
    return uploadFile(request)

def deleteDB(request):
    myFiles = File.objects.all()
    myFiles.delete()
    myFiles = mergedFile.objects.all()
    myFiles.delete()
    return render(request,'uploaded.html')


def uploadFile(request):
    user = (getNowUser())
    myFiles = File.objects.filter(user=user.userName)
    return render(request,'upload.html',{'files':myFiles,'user':user})

def uploadedFile(request):
    user = (getNowUser())
    myFiles = mergedFile.objects.filter(user=user.userName)
    return render(request,'uploaded.html',{'files':myFiles,'user':user})

AccountProject/myprofile/views.py
from django.shortcuts import render
from django.http import HttpResponse
from login.models import User
from login.views import getNowUser


# Create your views here.
def myprofile(request):
    user=(getNowUser())
    return render(request,f'myprofile.html',{'user':user}) 

def editprofilesubmit(request):
    user=(getNowUser())
    user.firstName=request.POST['firstName']
    user.lastName=request.POST['lastName']
    user.password=request.POST['password']
    user.email=request.POST['Email']
    user.phoneNumber=request.POST['phoneNumber']
    user.save()
    return render(request,f'myprofile.html',{'user':user})

def editprofile(request):
    user=(getNowUser())
    return render(request,'editprofile.html',{'user':user})

AccountProject/sendPdfs/views.py
from django.shortcuts import render
from myfile.models import File
from sendPdfs.models import mergedFile
from django.conf import settings
from django.core.mail import EmailMessage
from PyPDF2 import PdfFileMerger
import os
import datetime
import time
from twilio.rest import Client

def sendMail(nameFile,user):
    email = EmailMessage('Monthly Merged pdfs', f'Hi {user.userName},Sent your merged pdfs to email.', settings.EMAIL_HOST_USER, [user.email, ])
    email.attach_file(f'MergedPdfs\{nameFile}.pdf') 
    email.send()

def mergePdfs(user):
    closeMe = []
    nameFile="mergedFile"+str(datetime.datetime.now().date())
    x = [a for a in os.listdir('media/') if a.endswith(".pdf")]
    merger = PdfFileMerger()
    for pdf in x:
        y = open(f'media/{pdf}','rb')
        closeMe.append(y)
        merger.append(y)
    with open(f"MergedPdfs/{nameFile}.pdf", "wb") as fout:
        merger.write(fout)
    for pdf in closeMe:
        pdf.close()    
    for pdf in x:
        os.remove(f'media/{pdf}')      
    mergeFile=mergedFile(user=user.userName,name=nameFile,file=f'MergedPdfs/{nameFile}.pdf' )
    mergeFile.save()
    myFiles = File.objects.filter(user=user.userName)
    myFiles.delete()
    return nameFile

def sendWhatsapp(user):
    client = Client("ACc4fc9940599aafbc4b4a55a147271477","278416c2ddb8b1b72eb4a3bcafcdbac5")
    from_whatsapp_number='whatsapp:+14155238886'
    to_whatsapp_number = 'whatsapp:' + user.phoneNumber
    client.messages.create (body=f'Your documents has been sent to your Email: {user.email} by client: {user.userName}',
                            from_=from_whatsapp_number,
                            to=to_whatsapp_number)

def mergeAndSend(user):
    flag = True
    while True:
        if flag:
            flag = False
            if File.objects.filter(user=user.userName):
                if datetime.datetime.today().day == 14:  
                    sendWhatsapp(user) 
                    nameFile=mergePdfs(user)
                    sendMail(nameFile,user) 
        else:
            flag=True
            time.sleep((24*60*60))

AccountProject/login/templates/loginPage/login.html
{% load static %} 
    <link rel="stylesheet" href="{% static './cssLogin/cssLogin.css' %}"> 
    <div class="container">
    <div class="left-section">
    <div class="header">
        <h1 class="animation a1">Welcome</h1>
        <h4 class="animation a2">Log in for entering your member dashboard.</h4>
    </div>
    <div class="form">
        <form class="form" method="post" action="{% url 'login:submit_login' %}"> 
        {% csrf_token %}
            <input type="text" name="username" class="form-field animation a3" placeholder="Username" required>
            <input type="password" name="password" class="form-field animation a4" placeholder="Password" required>
            <button class="animation a6">LOGIN</button>
        </form>
        <form class="form" action="{% url 'login:register' %}">
            <button class="animation a6">Register</button>
        </form>
        <form class="form" action="{% url 'myfile:deleteDB' %}">
            <button class="animation a6">delete DB</button>
        </form>
         
        
        
    </div>
    </div>
    <div class="right-section"></div>
    </div>    
    

AccountProject/myfile/templates/profile/profile.html
{% load static %} 
<html>
<title>Client Page</title>
<meta charset="UTF-8">
<link rel="stylesheet" href="{% static 'profile.css' %}"> 
<link rel="stylesheet" href="{% static 'menu.css' %}"> 
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>

{% block body %}
<body class="w3-light-grey">

<!-- Top container -->

  <a class="w3-bar-item w3-right" href={% url 'login:homePage' %} style="font-size:31px;color:#ffffff;"> <i class="fa fa-sign-out"></i>  </a>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;margin-top:-44px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s8 w3-bar">
      
      <span >Welcome, <strong>{{user.firstName}}</strong></span>
      <a href={% url 'myprofile:myprofile' %} ><i class="fa fa-user"></i></a>
      

    </div>
  </div>
  <hr>
  <div class="w3-container">
    <h5>Dashboard</h5>
  </div>
  <div class="w3-bar-block">
    <a href={% url 'myfile:home' %} class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-home"></i>  Home </a>
    <a href={% url 'myfile:uploadedfile' %} class="w3-bar-item w3-button w3-padding"><i class="fa fa-id-card"></i>  My profile</a>
    <a href={% url 'myfile:uploadfile' %} class="w3-bar-item w3-button w3-padding"><i class="fa fa-cloud-upload"></i>  Upload invoice</a>
    <a href={% url 'myfile:uploadedfile' %} class="w3-bar-item w3-button w3-padding"><i class="fa fa-cloud"></i>  Uploaded invoices</a>
    
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">
<!-- CONTENT GOES HERE -->

<div class="container">
  <div class="aligner">
    <div class="card">

      <h4>FILE UPLOADER</h4>
      <div class="drop-area">
        <div class="file-upload">
          <div class="image-upload-wrap">
          <form action="{% url 'myfile:addFileButton' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
            <input id="myFile" class="file-upload-input" type='file' accept="" onchange="myFunction()" name="fileInput" multiple required/>
            <div class="drag-text" id="drag-text">
              <h2 id="nameChange">Drag and drop a file</h2>
            </div>
          </div>
          <br><br>
            <button class="file-upload-btn" type="submit">Add Files</button>
          </form>
        </div>
      </div>
      
      <div class="file-list">
        <div class="file-upload-content">
          
          <div class="uploaded-file"></div>
          
          <div class="image-title-wrap">
            <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span></button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

{% if messages %}
        {% for message in messages %}
            {% if message.tags %}<script>alert("{{ message }}")</script>
            {% endif %}
        {% endfor %}
{% endif %}


<script>
let number = 1;
  myFunction = () =>{
      let nme = document.getElementById("myFile").files;
      if(document.getElementById("myFile").files.length > 0) {
        for(let i = 0, size = nme.length; i < size ; i++){
          let item = nme[i];
          d1 = document.getElementById("drag-text");
          d1.insertAdjacentHTML('beforeend', "<h1>" + (number) + ") " +  item.name + "</h1>");
          number++;
      }
    }
  }  
</script>

  <!-- End page content -->
</div>


<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
    if (mySidebar.style.display === 'block') {
        mySidebar.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidebar.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidebar with the close button
function w3_close() {
    mySidebar.style.display = "none";
    overlayBg.style.display = "none";
}

//Uploading file
$(document).ready(function(){
  $('form input').change(function () {
    $('form p').text(this.files.length + " file(s) selected");
  });
});


</script>

</body>
{% endblock body %}
</html>

AccountProject/myfile/templates/upload.html
{% load static %} 
<html>
<title>Client Page</title>
<meta charset="UTF-8">
<link rel="stylesheet" href="{% static 'menu.css' %}"> 
<link rel="stylesheet" href="{% static 'showPdf.css' %}"> 
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>

{% block body %}
<body class="w3-light-grey">

<!-- Top container -->

  <a class="w3-bar-item w3-right" href={% url 'login:homePage' %} style="font-size:31px;color:#ffffff;"> <i class="fa fa-sign-out"></i>  </a>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;margin-top:-44px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s8 w3-bar">
      
      <span >Welcome, <strong>{{user.firstName}}</strong></span>
      <a href={% url 'myprofile:myprofile' %} ><i class="fa fa-user"></i></a>
      

    </div>
  </div>
  <hr>
  <div class="w3-container">
    <h5>Dashboard</h5>
  </div>
  <div class="w3-bar-block">
    <a href={% url 'myfile:home' %} class="w3-bar-item w3-button w3-padding"><i class="fa fa-home"></i>  Home </a>
    <a href={% url 'myprofile:myprofile' %} class="w3-bar-item w3-button w3-padding"><i class="fa fa-id-card"></i>  My profile</a>
    <a href={% url 'myfile:uploadfile' %} class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-upload"></i> Upload invoice</a>
    <a href={% url 'myfile:uploadedfile' %} class="w3-bar-item w3-button w3-padding"><i class="fa fa-cloud"></i>  Uploaded invoices</a>
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">
<!-- CONTENT GOES HERE -->

<div class="container" style="top: auto; right: -20%;display: grid; grid-template-columns: repeat(4, 0.2fr);">


{% for f in files %}
<div >
<div class="bodyPdf">
    <div class="cardPdf app-file-list">
  <div class="app-file-icon">
    <i class="fas fa-file-pdf" style="color: red; font-size: 60px"></i>
  </div>
  <div class="description">
    <div>
      <div>{{f.name}}.pdf</div>
      <div>{{f.date}}</div>
    </div>
    <div>
      <a href="{% url 'myfile:deleteFile' id=f.id %}" method="POST"><i class="fa fa-remove"></i></a>
    </div>
  </div>
</div>
</div>
    </div>
    {% endfor %}
  </div>
</div>
</div>
  <!-- End page content -->
</div>


</body>
{% endblock body %}
</html>

AccountProject/myfile/templates/uploaded.html
{% load static %} 
<html>
<title>Client Page</title>
<meta charset="UTF-8">
<link rel="stylesheet" href="{% static 'menu.css' %}"> 
<link rel="stylesheet" href="{% static 'showPdf.css' %}"> 
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>

{% block body %}
<body class="w3-light-grey">

<!-- Top container -->

  <a class="w3-bar-item w3-right" href={% url 'login:homePage' %} style="font-size:31px;color:#ffffff;"> <i class="fa fa-sign-out"></i>  </a>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;margin-top:-44px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s8 w3-bar">
      
      <span >Welcome, <strong>{{user.firstName}}</strong></span>
      <a href={% url 'myprofile:myprofile' %} ><i class="fa fa-user"></i></a>
      

    </div>
  </div>
  <hr>
  <div class="w3-container">
    <h5>Dashboard</h5>
  </div>
  <div class="w3-bar-block">
    <a href={% url 'myfile:home' %} class="w3-bar-item w3-button w3-padding"><i class="fa fa-home"></i>  Home </a>
    <a href={% url 'myprofile:myprofile' %} class="w3-bar-item w3-button w3-padding"><i class="fa fa-id-card"></i>  My profile</a>
    <a href={% url 'myfile:uploadfile' %} class="w3-bar-item w3-button w3-padding "><i class="fa fa-upload"></i> Upload invoice</a>
    <a href={% url 'myfile:uploadedfile' %} class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-cloud"></i>  Uploaded invoices</a>
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">
<!-- CONTENT GOES HERE -->

<div class="container" style="top: auto; right: -20%;display: grid; grid-template-columns: repeat(4, 0.2fr);">


{% for f in files %}
<div >
<div class="bodyPdf">
    <div class="cardPdf app-file-list">
  <div class="app-file-icon">
    <i class="fas fa-file-pdf" style="color: red; font-size: 60px"></i>
  </div>
  <div class="description">
    <div>
      <div>{{f.name}}.pdf</div>
      <div>{{f.date}}</div>
    </div>

  </div>
</div>
</div>
    </div>
    {% endfor %}
  </div>
</div>
</div>

  <!-- End page content -->
</div>
</body>
{% endblock body %}
</html>

AccountProject/myfile/templates/users/client.html
{% load static %} 
<html>
<title>Client Page</title>
<meta charset="UTF-8">
<link rel="stylesheet" href="{% static 'uploadFile.css' %}"> 
<link rel="stylesheet" href="{% static 'menu.css' %}"> 
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>

{% block body %}
<body class="w3-light-grey">

<!-- Top container -->

  <a class="w3-bar-item w3-right" href={% url 'login:homePage' %} style="font-size:31px;color:#ffffff;"> <i class="fa fa-sign-out"></i>  </a>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;margin-top:-44px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s8 w3-bar">
      
      <span >Welcome, <strong>{{user.firstName}}</strong></span>
      <a href={% url 'myprofile:myprofile' %} ><i class="fa fa-user"></i></a>
      

    </div>
  </div>
  <hr>
  <div class="w3-container">
    <h5>Dashboard</h5>
  </div>
  <div class="w3-bar-block">
    <a href={% url 'myfile:home' %} class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-home"></i>  Home </a>
    <a href={% url 'myprofile:myprofile' %} class="w3-bar-item w3-button w3-padding"><i class="fa fa-id-card"></i>  My profile</a>
    <a href={% url 'myfile:uploadfile' %} class="w3-bar-item w3-button w3-padding"><i class="fa fa-cloud-upload"></i>  Upload invoice</a>
    <a href={% url 'myfile:uploadedfile' %} class="w3-bar-item w3-button w3-padding"><i class="fa fa-cloud"></i>  Uploaded invoices</a>
    
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">
<!-- CONTENT GOES HERE -->

<div class="container">
  <div class="aligner">
    <div class="card" style="margin-left: -290px;">

      <h4>FILE UPLOADER</h4>
      <div class="drop-area">
        <div class="file-upload">
          <div class="image-upload-wrap">
          <form action="{% url 'myfile:addFileButton' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
            <input id="myFile" class="file-upload-input" type='file' accept="" onchange="myFunction()" name="fileInput" multiple required/>
            <div class="drag-text" id="drag-text">
            {% if messages %}
              {% for message in messages %}
                {% if message.tags %}<h2>{{ message }}</h2>
                {% endif %}
              {% endfor %}
                
            {% else %}
              <h2 id="nameChange">Drag and drop a file</h2>
            {% endif %}
            </div>
          </div>
          <br><br>
            <button class="file-upload-btn" onclick="submitFunc()" type="submit">Add Files</button>
          </form>
        </div>
      </div>
      
      <div class="file-list">
        <div class="file-upload-content">
          
          <div class="uploaded-file"></div>
          
          <div class="image-title-wrap">
            <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span></button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>



<script>
  myFunction = () =>{
      let nme = document.getElementById("myFile").files;
      if(document.getElementById("myFile").files.length > 0) {
        for(let i = 0, size = nme.length; i < size ; i++){
          let item = nme[i];
          let d1 = document.getElementById("drag-text");
          d1.insertAdjacentHTML('beforeend', "<h4><b>" +  item.name + "<b></h4>");
      }
    }
  }  
  submitFunc = () =>{
    let d1 = document.getElementById("nameChange");
    d1.innerText = "Succesfuly" 
  }
</script>

  <!-- End page content -->
</div>


<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
    if (mySidebar.style.display === 'block') {
        mySidebar.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidebar.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidebar with the close button
function w3_close() {
    mySidebar.style.display = "none";
    overlayBg.style.display = "none";
}

</script>

</body>
{% endblock body %}
</html>